jenkins-slave:
  environment:
    JENKINS_USERNAME: jenkins
    JENKINS_PASSWORD: jenkins
    JENKINS_MASTER: http://jenkins-master:8080
  privileged: true
  image: jenkins-slave
  links:
  - jenkins-master:jenkins-master
  volumes:
    - /var/jenkins

jenkins-master:
  image: jenkins
  environment:
    JAVA_OPTS: "-Dhudson.footerURL=http://camptocamp.com"
  volumes:
    - jenkinshome:/var/jenkins_home
  ports:
    - "8080:8080"
