---
jobber:
  image: blacklabelops/cron-cloud
  environment:
    JOB_NAME1: conplicity
    JOB_COMMAND1: docker start r-conplicity-conplicity-1
    JOB_TIME1: 0 ${CONPLICITY_RUN_TIME}
  labels:
    io.rancher.scheduler.global: 'true'
  tty: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
conplicity:
  image: camptocamp/conplicity:latest
  environment:
    DUPLICITY_TARGET_URL: ${DUPLICITY_TARGET_URL}
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
  tty: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock:ro
