slave:
  environment:
    JENKINS_USERNAME: jenkins
    JENKINS_PASSWORD: jenkins
    JENKINS_MASTER: http://jenkins-master:8080
  privileged: true
  image: jenkins-slave
  links:
  - master:master
  volumes:
    - /var/jenkins

master:
  image: jenkins
  environment:
    # 0 means random
    JENKINS_SLAVE_AGENT_PORT: 0
  #    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
  volumes:
    - jenkinshome:/var/jenkins_home
    - ./config.xml:/var/jenkins_home/config.xml
  ports:
    - "8080:8080"

#master-conf:
#build: conf
