slave:
  environment:
    JENKINS_USERNAME: jenkins
    JENKINS_PASSWORD: jenkins
    JENKINS_MASTER: http://master:8080
  privileged: true
  image: jenkins-slave
  links:
    - master:master
  volumes:
    - /var/jenkins

master:
  image: jenkins
  environment:
    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    JENKINS_ADMIN_USERNAME: jenkins
    JENKINS_ADMIN_PASSWORD: jenkins
  volumes_from:
    - master-conf
  volumes:
    - jenkinshome:/var/jenkins_home
  ports:
    - "8080:8080"

master-conf:
  build: conf
