---
gogs:
  image: gogs/gogs:0.9.13
  ports:
    - ${GOGS_SSH_PORT}:22
  external_links:
    - ${GOGS_DATABASE_SERVICE}:db
  volumes:
    - gogs-data:/data

auth:
  image: camptocamp/oauth2_proxy:github_user
  command:
    - -http-address=0.0.0.0:4180
    - -upstream=http://gogs:3000/
    - -provider=github
    - -client-id=${OAUTH_CLIENT_ID}
    - -client-secret=${OAUTH_CLIENT_SECRET}
    - -github-org=${OAUTH_GITHUB_ORG}
    - -github-team=${OAUTH_GITHUB_TEAM}
    - -cookie-secret=${OAUTH_COOKIE_SECRET}
    - -cookie-secure=false
    - -cookie-domain=${OAUTH_COOKIE_DOMAIN}
    - -cookie-name=_gogs_oauth2_proxy
    - -email-domain=*
    - -redirect-url=https://${GOGS_ROOT_URL}/oauth2/callback
  links:
    - gogs

lb:
  image: rancher/load-balancer-service
  links:
    - auth
  ports:
    - 443:4180
  labels:
    io.rancher.loadbalancer.ssl.ports: '443'
