puppetserver:
  hostname: ${PUPPET_DOMAIN}
  image: camptocamp/puppetserver:latest
  links:
  - puppetdb:puppetdb
  volumes:
  - puppetca:/etc/puppetlabs/puppet/ssl
  volume_driver: convoy-gluster
postgresql:
  image: camptocamp/puppetdb_postgres:latest
lb-puppet:
  ports:
  - 8140:8140/tcp
  image: rancher/load-balancer-service
  hostname: puppetdb
  links:
  - puppetserver:puppetserver
puppetdb:
  hostname: puppetdb
  image: camptocamp/puppetdb:latest
  links:
  - postgresql:postgresql
  volumes:
  - puppetca:/etc/puppetlabs/puppet/ssl
  volume_driver: convoy-gluster
