jenkins-slave:
  environment:
    JENKINS_USERNAME: jenkins
    JENKINS_PASSWORD: jenkins
    JENKINS_MASTER: http://jenkins-master:8080
  privileged: true
  image: jenkins-slave
  links:
  - jenkins-master:jenkins-master
  volumes:
    - /var/jenkins

jenkins-master:
  image: jenkins-master
  volumes:
    - /var/jenkins_home
  ports:
    - "8080:8080"
