puppetserver:
  ports:
  - 8140:8140/tcp
  environment:
    CERTNAME: ${CERTNAME}
  image: camptocamp/puppetserver:latest
  volumes:
  - puppetca:/etc/puppetlabs/puppet/ssl
  - puppetcode:/etc/puppetlabs/code/environments
  - puppetr10kcache:/opt/puppetlabs/r10k/cache
  volume_driver: convoy-gluster
postgresql:
  image: camptocamp/puppetdb_postgres:latest
  volumes:
  - puppetdb_database:/var/lib/postgresql/data
  volume_driver: convoy-gluster
puppetboard:
  image: camptocamp/puppetboard:global_default
puppetdb:
  environment:
    ENABLE_HTTP: 'true'
  hostname: puppetdb
  image: camptocamp/puppetdb:latest
  volumes:
  - puppetca:/etc/puppetlabs/puppet/ssl
  volume_driver: convoy-gluster
