.catalog:
  name: "Puppet"
  version: "v2.2.1-c2c0"
  description: "Puppet Master stack"
  uuid: puppet-0
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "VOL_CA"
      label: "Puppet CA volume name"
      description: "Puppet CA volume name"
      default: "puppetca"
      type: "string"
      required: true
