.catalog:
  name: "Puppet"
  version: "v2.2.1-c2c2"
  description: "Puppet Master stack"
  uuid: puppet-0
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "CERTNAME"
      label: "Puppetmaster certname"
      description: "Puppet domain to use (certname)"
      type: "string"
      required: true
