puppetserver:
  ports:
  - 8140:8140/tcp
  environment:
    CERTNAME: ${CERTNAME}
  image: camptocamp/puppetserver:latest
  volumes:
  - ${VOL_CA}:/etc/puppetlabs/puppet/ssl
  - ${VOL_CODE}:/etc/puppetlabs/code/environments
  volume_driver: convoy-gluster
postgresql:
  image: camptocamp/puppetdb_postgres:latest
  volumes:
  - ${VOL_DB}:/var/lib/postgresql/data
  volume_driver: convoy-gluster
puppetboard:
  image: camptocamp/puppetboard:global_default
puppetdb:
  environment:
    ENABLE_HTTP: 'true'
  hostname: puppetdb
  image: camptocamp/puppetdb:latest
  volumes:
  - ${VOL_CA}:/etc/puppetlabs/puppet/ssl
  volume_driver: convoy-gluster
