puppetserver:
  ports:
  - 8140:8140/tcp
  environment:
    CERTNAME: ${CERTNAME}
    DNS_ALT_NAMES: ${DNS_ALT_NAMES}
  image: camptocamp/puppetserver:latest
  volumes:
  - ${VOL_CA}:/etc/puppetlabs/puppet/ssl
  - ${VOL_CODE}:/etc/puppetlabs/code/environments
  - ${VOL_R10KCACHE}:/opt/puppetlabs/r10k/cache
  volume_driver: convoy-gluster
postgresql:
  image: camptocamp/puppetdb_postgres:latest
  volumes:
  - ${VOL_DB}:/var/lib/postgresql/data
  volume_driver: convoy-gluster
puppetboard:
  image: camptocamp/puppetboard:global_default
puppetdb:
  environment:
    ENABLE_HTTP: 'true'
  hostname: puppetdb
  image: camptocamp/puppetdb:latest
  volumes:
  - ${VOL_CA}:/etc/puppetlabs/puppet/ssl
  volume_driver: convoy-gluster
r10k:
  image: camptocamp/r10k-githook:entrypoint
  environment:
    PASSWORD: ${PASSWORD}
  ports:
  - 2222:22/tcp
  volumes:
  - ${VOL_CODE}:/etc/puppetlabs/code/environments
  - ${VOL_GIT}:/srv/puppetmaster.git
  - ${VOL_R10KCACHE}:/opt/puppetlabs/r10k/cache
  volume_driver: convoy-gluster
